---
title: "Host repertory model example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{coin-example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE
)
```

```{r setup}
library(treepplr)
library(ggplot2)
library(magrittr)
if(!require("evolnets", quietly = TRUE)) {
  library(devtools)
  if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

  BiocManager::install("ggtree")
  BiocManager::install("treeio")
  devtools::install_github("maribraga/evolnets")
} else {
  library(evolnets)
}
```

Run the `hostrep.tppl` TreePPL program using the created input data. 

```{r}
model <- tp_model("hostrep3states")
data <- tp_data("hostrep3states")
output_json <- tp_treeppl(model = model, model_name = "hostrep", data = data, data_name = "hostrep")
```

```{r}
output <- tp_parse(output_json)
```

Prepare the post-treatment function

```{r}
get_history <- function(parsed_output){
  hist <- data.frame()
  for(i in seq_along(parsed_output)){
    
    table <- parsed_output[[i]] %>% 
      dplyr::select(-c(log_weight, mu, beta, lambda1, lambda2, lambda3, lambda4)) %>%
      dplyr::mutate(transition_type = "anagenetic") %>% 
      dplyr::mutate(node_index = dplyr::case_when(node_index == 3 ~ 5, # ugly fix to node_index mismatch and 0- to 1-base
                                    node_index == 4 ~ 4,
                                    TRUE ~ node_index + 1)) %>% 
      dplyr::filter(!is.na(log_norm_const)) %>% 
      dplyr::mutate(sweep = i, .before = "iteration") %>% 
      unique() %>% 
      dplyr::mutate(iteration = as.numeric(paste0(sweep, iteration))) %>% 
      dplyr::select(-sweep)
    
    hist <- rbind(hist, table)
  }
  
  # sample based on norm const?
  # or change posterior_at_nodes?
  
  return(hist)
}
```

Add complementary data

```{r}
symbiont_tree <- evolnets::read_tree_from_revbayes(paste0(system.file("extdata", package = "treepplr"),
                                                          "/tree_subroot_Rev.tre"))
host_tree <- treeio::read.tree(paste0(system.file("extdata", package = "treepplr"), 
                             "/host_tree.tre"))
matrix <- read.csv(paste0(system.file("extdata", package = "treepplr"), 
                             "/host_matrix.csv"), row.names = 1) %>% as.matrix()
```
  
Plot the posterior distribution.

```{r}
# history is together with the logs
tp_hist <- get_history(output)

# calculate posterior at nodes
tp_at_nodes <- evolnets::posterior_at_nodes(tp_hist, symbiont_tree, host_tree, state = c(1,2))

# plot data nad ancestral states
(tp_asr_fund <- evolnets::plot_matrix_phylo(matrix, tp_at_nodes, symbiont_tree, host_tree, type = "repertoires", repertoire = "fundamental"))
(tp_asr_real <- evolnets::plot_matrix_phylo(matrix, tp_at_nodes, symbiont_tree, host_tree, type = "repertoires", repertoire = "realized"))
```
